import { AppData } from '../types';

export const initialData: AppData = {
  profile: {
    id: 'default-profile-1',
    nama: 'Rania Pratama',
    nama_aksen: 'Rania',
    nama_sisa: 'Pratama',
    tagline: 'Brand Designer & Visual Communication Strategist',
    deskripsi: 'Praktisi desain komunikasi visual dan branding dengan pengalaman lebih dari 5 tahun dalam merancang identitas merek, kampanye kreatif, serta strategi konten visual untuk organisasi, korporat, dan UMKM berkembang.',
    status: 'Terbuka untuk Kolaborasi',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80',
    resume_url: 'https://drive.google.com/file/d/1ExampleResumePortfolio/view?usp=sharing',
    updated_at: new Date().toISOString(),
  },
  skills: [
    { id: 'sk-1', nama: 'Canva', urutan: 1 },
    { id: 'sk-2', nama: 'Adobe Illustrator', urutan: 2 },
    { id: 'sk-3', nama: 'Adobe Photoshop', urutan: 3 },
    { id: 'sk-4', nama: 'Brand Identity Strategy', urutan: 4 },
    { id: 'sk-5', nama: 'Microsoft Office & Word', urutan: 5 },
    { id: 'sk-6', nama: 'Visual Storytelling', urutan: 6 },
    { id: 'sk-7', nama: 'Copywriting Kampanye', urutan: 7 },
    { id: 'sk-8', nama: 'Social Media Management', urutan: 8 },
    { id: 'sk-9', nama: 'Public Speaking & Presentasi', urutan: 9 },
    { id: 'sk-10', nama: 'Art Direction', urutan: 10 },
  ],
  projects: [
    {
      id: 'proj-1',
      judul: 'Rebranding Identitas Nusantara Coffee & Roastery',
      deskripsi: 'Pengembangan identitas visual menyeluruh, mulai dari logo modern, kemasan ramah lingkungan, pedoman tipografi, hingga materi promosi outlet untuk jaringan kedai kopi lokal.',
      gambar_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
      link: 'https://drive.google.com/drive/folders/sample-branding-nusantara',
      urutan: 1,
    },
    {
      id: 'proj-2',
      judul: 'Kampanye Edukasi Nutrisi Keluarga Sehat',
      deskripsi: 'Pembuatan infografis visual, video presentasi animasi singkat di Google Drive, dan buklet panduan praktis untuk program CSR nutrisi anak usia dini.',
      gambar_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
      link: 'https://drive.google.com/file/d/sample-edukasi-video-animasi/view',
      urutan: 2,
    },
    {
      id: 'proj-3',
      judul: 'Laporan Keberlanjutan & Annual Report Visual PT Kreasi Mandiri',
      deskripsi: 'Tata letak editorial laporan tahunan setebal 72 halaman dengan infografis data terstruktur, tipografi harmonis, dan format siap cetak serta digital interaktif.',
      gambar_url: 'https://images.unsplash.com/photo-1455849318743-b2233052fcff?auto=format&fit=crop&w=800&q=80',
      link: 'https://drive.google.com/file/d/sample-annual-report-pdf/view',
      urutan: 3,
    },
    {
      id: 'proj-4',
      judul: 'Desain Merchandise & Brand Kit Festival Seni Budaya 2025',
      deskripsi: 'Perancangan aset visual festival musik dan seni budaya tradisional termasuk kaos, totebag, poster promosi kota, dan tiket masuk eksklusif.',
      gambar_url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
      link: 'https://drive.google.com/drive/folders/sample-festival-merchandise',
      urutan: 4,
    },
  ],
  experiences: [
    {
      id: 'exp-1',
      instansi: 'Studio Cerita Kreatif',
      peran: 'Senior Brand & Visual Designer',
      tahun: '2023 — Sekarang',
      lokasi: 'Jakarta Selatan, Indonesia',
      deskripsi: 'Memimpin perancangan identitas visual untuk 25+ klien korporat dan institusi, mengarahkan tim desainer junior, dan menyelaraskan komunikasi merek di berbagai kanal.',
      urutan: 1,
    },
    {
      id: 'exp-2',
      instansi: 'Yayasan Lentera Pendidikan',
      peran: 'Koordinator Komunikasi & Publikasi',
      tahun: '2021 — 2023',
      lokasi: 'Bandung, Indonesia',
      deskripsi: 'Mengelola produksi materi visual publikasi tahunan, media sosial, serta kurikulum visual untuk program pelatihan guru di pelosok daerah.',
      urutan: 2,
    },
    {
      id: 'exp-3',
      instansi: 'Agensi Media Warna Citra',
      peran: 'Graphic Designer & Content Specialist',
      tahun: '2019 — 2021',
      lokasi: 'Surabaya, Indonesia',
      deskripsi: 'Merancang aset visual kampanye digital, layout majalah korporat, serta materi presentasi promosi untuk beragam klien industri ritel dan hospitality.',
      urutan: 3,
    },
  ],
  courses: [
    {
      id: 'crs-1',
      nama_course: 'Executive Masterclass: Strategic Brand Architecture',
      penyelenggara: 'Design Leadership Academy & Brand Institute',
      tahun: '2024',
      lokasi: 'Daring (Online)',
      deskripsi: 'Pendalaman metodologi riset positioning merek, audit visual pasar, dan pengembangan guideline identitas skala enterprise.',
      urutan: 1,
    },
    {
      id: 'crs-2',
      nama_course: 'Sertifikasi Tata Kelola Desain Publikasi & Editorial',
      penyelenggara: 'Pusat Pelatihan Komunikasi Kreatif Nasional',
      tahun: '2022',
      lokasi: 'Jakarta, Indonesia',
      deskripsi: 'Pelatihan intensif layout cetak profesional, manajemen warna prepress, dan standar aksesibilitas dokumen publik.',
      urutan: 2,
    },
    {
      id: 'crs-3',
      nama_course: 'Visual Storytelling for Community Impact',
      penyelenggara: 'Southeast Asia Creative Hub',
      tahun: '2020',
      lokasi: 'Yogyakarta, Indonesia',
      deskripsi: 'Workshop penceritaan visual berbasis advokasi masyarakat dan desain materi komunikasi berbasis empati.',
      urutan: 3,
    },
  ],
  languages: [
    { id: 'lang-1', nama_bahasa: 'Bahasa Indonesia', level: 'Native' },
    { id: 'lang-2', nama_bahasa: 'Bahasa Inggris', level: 'Intermediate' },
  ],
  contacts: [
    {
      id: 'cnt-1',
      tipe: 'whatsapp',
      label: 'WhatsApp',
      value: '+62 812-3456-7890',
      link: 'https://wa.me/6281234567890?text=Halo%20Rania,%20saya%20tertarik%20untuk%20berkolaborasi.',
    },
    {
      id: 'cnt-2',
      tipe: 'email',
      label: 'Email',
      value: 'rania.pratama.design@gmail.com',
      link: 'mailto:rania.pratama.design@gmail.com?subject=Inquiry%20Kolaborasi%20Portofolio',
    },
    {
      id: 'cnt-3',
      tipe: 'instagram',
      label: 'Instagram',
      value: '@rania.visuals',
      link: 'https://instagram.com/rania.visuals',
    },
    {
      id: 'cnt-4',
      tipe: 'linkedin',
      label: 'LinkedIn',
      value: 'linkedin.com/in/raniapratama',
      link: 'https://linkedin.com/in/raniapratama',
    },
  ],
};
